#pragma once
#include "../model/db.h"

enum actions {
    PROD_DESCRIPTION,
    PRINT_SHELVES,
    ADD_COSMETIC,
    ADD_MEDICINE,
    GET_STOCK_REPORT,
    REMOVE_PRODUCT,
    ADD_SUPPLIER,
    REMOVE_SUPPLIER,
    PRINT_SUPPLIER_INFO,
    PRINT_SUPPLIER_PROD,
    ADD_ADDRESS,
    REMOVE_ADDRESS,
    ADD_CONTACT,
    REMOVE_CONTACT,
    ADD_BOX,
    GET_EXPIRY_REPORT,
    ADD_SHELF,
    UPDATE_SHELF,
    SEND_LETTER,
    PRINT_LETTERS,
    PRINT_SALES_DATE,
    PRINT_SALES_PROD,
    PRINT_MOST_SOLD,
    QUIT,
    END_OF_ACTIONS
};

extern int get_administrative_action(void);